name: Deploy To GKE

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - id: auth
      uses: google-github-actions/auth@v3
      with:
        workload_identity_provider: projects/687523369801/locations/global/workloadIdentityPools/github-pol/providers/github-provider-v2
        service_account: 687523369801-compute@developer.gserviceaccount.com

    - uses: google-github-actions/setup-gcloud@v2

    - run: |
        gcloud container clusters get-credentials cluster-1 \
          --region europe-west1 \
          --project tushar-prometheus-live

    - run: |
        kubectl apply -f k8s/
