name: Deploy To GKE

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v3
        with:
          workload_identity_provider: projects/687523369801/locations/global/workloadIdentityPools/github-pol/providers/github-provider-v2
          service_account: 687523369801-compute@developer.gserviceaccount.com

      - name: Setup GCloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Get GKE Credentials
        uses: google-github-actions/get-gke-credentials@v3
        with:
          cluster_name: cluster-1
          location: europe-west1

      - name: Verify Connection
        run: |
          kubectl get nodes

      - name: Deploy
        run: |
          kubectl apply -f deployment.yaml
          kubectl get pods
